# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lightning Network SMS Payment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    
    - name: Run Black check
      run: |
        pipenv run black --check ./
        
    - name: Run Flake8 check
      run: |
        mkdir test-reports
        pipenv run flake8 ./ -v --output-file test-reports/flake8
    
    - name: Upload flake test results
      uses: actions/upload-artifact@master
      with:
          name: flake8-report
          path: test-reports/flake8
      # Use failure() to upload only if failure occurs
      if: failure()

    - name: Running migrations and tests
      env:
        DJANGO_CONFIGURATION: 'Testing'
      run: |
        pipenv run python manage migrate
        pipenv run python manage test -v 2
